<link media="all" rel="stylesheet" type="text/css" href="dpnd/css/3duser.css"/><div id="wrapper">    <?php    $ud = loadDB('users\\'.$_GET['user']);    if(isset($ud['profile']))    {        $settings = array_replace($settings, $ud['profile']);
    }    $ver = sendjson('players.name', '"'.$_GET['user'].'"');    $ver = json_decode($ver);    echo '    <center><h1 style="margin-top:-10px;display:inline-block;">'.$_GET['user'].'\'s Profile</h1>    </center>    ';    if(!(isset($settings['pp-3duser']) and $settings['pp-3duser'] == 'false'))    {        echo '<style>#wrapper {min-height:460px;}</style><div id="skinpreview"></div>';
    }    echo '    <hr>    <center>    <a id="button" href="./?act=3duser&user='.$_GET['user'].'">Refresh <span id="refreico"></span></a>    ';    if(!(isset($settings['pp-stealskin']) and $settings['pp-stealskin'] == 'false'))    {        echo '<a id="button" target="_blank" href="http://skins.minecraft.net/MinecraftSkins/'.$_GET['user'].'.png" download="'.$_GET['user'].' Skin">Steal '.$_GET['user'].'\'s Skin <span id="downico"></span></a>';
    }        if(isloggedin() and (username() !== $_GET['user']) and isregistered($_GET['user']) and !(isset($settings['messagesenabled']) and $settings['messagesenabled'] == 'false'))    {        echo '<a id="button" href="./?act=viewmessages&new&autouser='.$_GET['user'].'">Message <span id="chatico"></span></a>';    }    echo '<hr>';    if(isset($ver[0]->success))    {        //Do work up here then output it below yo.        function displhealth($perc)        {            $percdec = $perc / 100;            $full = 180;            $fh = $full * $percdec;            $eh = $full - ($full * $percdec);            return '<span style="width:'.$fh.'px" id="fh"></span><span style="width:'.$eh.'px" id="eh"></span>';        }        function displhunger($perc)        {            $percdec = $perc / 100;            $full = 180;            $fh = $full * $percdec;            $eh = $full - ($full * $percdec);            return '<span style="width:'.$eh.'px" id="ehb"></span><span style="width:'.$fh.'px" id="fhb"></span>';        }        function dispinventory()        {            global $ver;            $num = 0;            echo '<table>';            $afternin = array_slice($ver[0]->success->inventory->inventory,9);            $firstnin = array_slice($ver[0]->success->inventory->inventory,0,9);            foreach(array_merge($afternin,$firstnin) as $item)            {                $num++;                if(isset($item->amount) and $item->amount !== 1)                {                    $amm = $item->amount;                }                else                {                    $amm = null;                }                if($num % 9 === 9)                {                    echo '<tr>';                }                echo '<td><img title="'.mcitemname(@$item->type, @$item->dataValue).'" src="dpnd/images/mcitems/'.mcitemname(@$item->type, @$item->dataValue, true).'.png" id=""><span id="amm">'.$amm.'</span></td>                ';                if($num % 9 === 0)                {                    echo '</tr>';                }            }            echo '</table>';        }        //////////////////////////////////////////        if(!(isset($settings['pp-status']) and $settings['pp-status'] == 'false'))        {            echo '            <fieldset>                <legend>Status</legend>';                if(isset($ver[0]->success->ip) and $ver[0]->success->ip !== 'offline')                {                    echo 'Online';                }                else                {                    echo 'Offline';                }                echo '            </fieldset>            ';
        }        if(!(isset($settings['pp-currenthealth']) and $settings['pp-currenthealth'] == 'false'))        {            echo '            <fieldset title="'.($ver[0]->success->health) * (5).'%">                <legend>Current Health</legend>                '.displhealth(($ver[0]->success->health) * (5)).'            </fieldset>            ';
        }        if(!(isset($settings['pp-currenthunger']) and $settings['pp-currenthunger'] == 'false'))        {            echo '            <fieldset title="'.($ver[0]->success->foodLevel) * (5).'%">                <legend>Current Hunger</legend>                '.displhunger(($ver[0]->success->foodLevel) * (5)).'            </fieldset>            ';
        }        if(!(isset($settings['pp-lastplayed']) and $settings['pp-lastplayed'] == 'false'))        {            echo '            <fieldset>                <legend>Last Played</legend>                '.date('Y-m-d, g:i a', $ver[0]->success->lastPlayed).'            </fieldset>            ';
        }        if(!(isset($settings['pp-firstjoined']) and $settings['pp-firstjoined'] == 'false'))        {            echo '            <fieldset>                <legend>First Joined</legend>                '.date('Y-m-d, g:i a', $ver[0]->success->firstPlayed).'            </fieldset>            ';
        }        if(!(isset($settings['pp-currentexperience']) and $settings['pp-currentexperience'] == 'false'))        {            echo '            <fieldset>                <legend>Current Experience</legend>                '.$ver[0]->success->experience.'            </fieldset>            '; 
        }        if(!(isset($settings['pp-currentworld']) and $settings['pp-currentworld'] == 'false'))        {            echo '            <fieldset>                <legend>Current World</legend>                '.$ver[0]->success->worldInfo->name.'            </fieldset>            ';
        }        if(!(isset($settings['pp-gamemode']) and $settings['pp-gamemode'] == 'false'))        {            echo '            <fieldset>                <legend>Gamemode</legend>                '.$ver[0]->success->gameMode.'            </fieldset>            ';
        }        if(!(isset($settings['pp-level']) and $settings['pp-level'] == 'false'))        {            echo '            <fieldset>                <legend>Level</legend>                '.$ver[0]->success->level.'            </fieldset>            ';
        }        if(!(isset($settings['pp-location']) and $settings['pp-location'] == 'false'))        {            echo '            <fieldset>                <legend>Location</legend>                X:'.round($ver[0]->success->location->x).' Z:'.round($ver[0]->success->location->z).'            </fieldset>            ';
        }        if(!(isset($settings['pp-iteminhand']) and $settings['pp-iteminhand'] == 'false'))        {            echo '            <fieldset>                <legend>Item In Hand</legend>                '.mcitemname($ver[0]->success->itemInHand->type, $ver[0]->success->itemInHand->dataValue).' <img src="dpnd/images/mcitems/'.mcitemname($ver[0]->success->itemInHand->type, $ver[0]->success->itemInHand->dataValue, true).'.png" id="blkimg"></img>            </fieldset>            ';
        }        if(!(isset($settings['pp-currentinventory']) and $settings['pp-currentinventory'] == 'false'))        {            echo '            <hr>            <fieldset style="height:auto;">                <legend>Current Inventory</legend>                ';            dispinventory();            echo '            </fieldset>';
        }    echo '    </center>    ';    }    else    {        Echo '    <h2>        <center>Statistics not available.</center>    </h2>    ';    }    echo '    <script src="dpnd/js/three.js"></script>    <script>        var defaultImages = [            "dpnd/skinheadapi.php?player='.$_GET['user'].'&skinonly"        ];    </script>    <script src="dpnd/js/main.js"></script>    ';    ?></div>